language: go

go:
  - master

git:
  depth: 1

branches:
  only:
  - master

go_import_path: hidevops.io/mio

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v

env:
  - APP_PROFILES_ACTIVE=local

script:
  - go test -v ./... -coverprofile=coverage.out -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

