FROM docker.vpclub.cn/hidevopsio/s2i-nodejs

RUN mkdir ${HOME}/vpclub/ && chmod 755 ${HOME}/vpclub

WORKDIR ${HOME}/vpclub

COPY node ${HOME}/vpclub/node

COPY config/ ${HOME}/vpclub/config/

ENV npm_config_registry ${npm_config_registry}
ENV npm_config_disturl https://npm.taobao.org/dist/
ENV npm_config_phantomjs_cdnurl https://npm.taobao.org/dist/phantomjs/
ENV npm_config_phantomjs_cdnurl https://npm.taobao.org/dist/phantomjs/
ENV npm_config_electron_mirror https://npm.taobao.org/mirrors/electron/
ENV npm_config_sass_binary_site https://npm.taobao.org/mirrors/node-sass/

EXPOSE 7575
EXPOSE 8080

CMD ["./node"]