// Code generated by MockGen. DO NOT EDIT.
// Source: hidevops.io/mio/node/pkg/service (interfaces: BuildConfigService)

// Package service is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	protobuf "hidevops.io/mio/node/protobuf"
	reflect "reflect"
)

// MockBuildConfigService is a mock of BuildConfigService interface
type MockBuildConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockBuildConfigServiceMockRecorder
}

// MockBuildConfigServiceMockRecorder is the mock recorder for MockBuildConfigService
type MockBuildConfigServiceMockRecorder struct {
	mock *MockBuildConfigService
}

// NewMockBuildConfigService creates a new mock instance
func NewMockBuildConfigService(ctrl *gomock.Controller) *MockBuildConfigService {
	mock := &MockBuildConfigService{ctrl: ctrl}
	mock.recorder = &MockBuildConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBuildConfigService) EXPECT() *MockBuildConfigServiceMockRecorder {
	return m.recorder
}

// Clone mocks base method
func (m *MockBuildConfigService) Clone(arg0 *protobuf.SourceCodePullRequest) (string, error) {
	ret := m.ctrl.Call(m, "Clone", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clone indicates an expected call of Clone
func (mr *MockBuildConfigServiceMockRecorder) Clone(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockBuildConfigService)(nil).Clone), arg0)
}

// Compile mocks base method
func (m *MockBuildConfigService) Compile(arg0 *protobuf.CompileRequest) error {
	ret := m.ctrl.Call(m, "Compile", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compile indicates an expected call of Compile
func (mr *MockBuildConfigServiceMockRecorder) Compile(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockBuildConfigService)(nil).Compile), arg0)
}

// ImageBuild mocks base method
func (m *MockBuildConfigService) ImageBuild(arg0 *protobuf.ImageBuildRequest) error {
	ret := m.ctrl.Call(m, "ImageBuild", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImageBuild indicates an expected call of ImageBuild
func (mr *MockBuildConfigServiceMockRecorder) ImageBuild(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageBuild", reflect.TypeOf((*MockBuildConfigService)(nil).ImageBuild), arg0)
}

// ImagePush mocks base method
func (m *MockBuildConfigService) ImagePush(arg0 *protobuf.ImagePushRequest) error {
	ret := m.ctrl.Call(m, "ImagePush", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImagePush indicates an expected call of ImagePush
func (mr *MockBuildConfigServiceMockRecorder) ImagePush(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImagePush", reflect.TypeOf((*MockBuildConfigService)(nil).ImagePush), arg0)
}
